#!/usr/bin/env python

from __future__ import annotations

import json
from pathlib import Path

from src.agents.portfolio_manager import portfolio_management_agent
from src.agents.risk_manager import risk_management_agent
from src.utils.analysts import ANALYST_CONFIG


EXTRA_PERSONAS = {
    "risk_manager": {
        "display_name": "Risk Manager",
        "investing_style": "Risk guardrail enforcer balancing gross/net exposure, overrides, and constraint hygiene.",
        "agent_func": risk_management_agent,
    },
    "portfolio_manager": {
        "display_name": "Portfolio Manager",
        "investing_style": "Final arbiter combining analyst signals with risk posture to issue executable orders.",
        "agent_func": portfolio_management_agent,
    },
}

DEFAULT_CONSTRAINTS = [
    "Maintain anthropomorphic voice aligned with persona",
    "Base decisions on supplied observation payload; avoid deterministic heuristics",
]

DEFAULT_WEAKNESSES = [
    "Requires refreshed observation payload annotations",
    "Prompt calibration pending for evolutionary arena export",
]


def format_persona_payload(key: str, config: dict) -> dict:
    func = config.get("agent_func")
    module = getattr(func, "__module__", None)
    func_name = getattr(func, "__name__", None)

    display_name = config.get("display_name", key.replace("_", " ").title())
    investing_style = config.get("investing_style") or config.get("description") or ""

    return {
        "persona_id": key,
        "display_name": display_name,
        "investing_style": investing_style,
        "module": module,
        "entrypoint": func_name,
        "prompt_reference": f"{module}.{func_name}" if module and func_name else None,
        "prompt_summary": "TODO: summarize persona system instructions and tone guidance.",
        "observation_schema": {
            "summary": "TODO: document observation payload keys and semantics.",
        },
        "constraints": list(DEFAULT_CONSTRAINTS),
        "known_weaknesses": list(DEFAULT_WEAKNESSES),
        "notes": [
            "Autogenerated stub – refine prompt_summary, observation_schema, constraints, and weaknesses.",
        ],
    }


def main() -> None:
    output_dir = Path("configs/persona_genomes")
    output_dir.mkdir(parents=True, exist_ok=True)

    all_configs = {**ANALYST_CONFIG, **EXTRA_PERSONAS}
    for persona_id, config in sorted(all_configs.items()):
        payload = format_persona_payload(persona_id, config)
        path = output_dir / f"{persona_id}.json"
        if path.exists():
            continue
        path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
        print(f"Created stub genome config {path}")


if __name__ == "__main__":
    main()
